#------Nodes------#
[lxcs]
# Technitium Internal DNS server
technitium-dns ansible_host=10.10.0.20
# Hashicorp Vault
hcp-vault ansible_host=10.10.0.30
# Github CI/CD Runner
github-ci-runner ansible_host=10.10.0.40

[vms]
# Portainer VM
portainer-vm ansible_host=10.20.0.10 ansible_user=admin
# K3s Cluster Nodes
k3s-control-node ansible_host=10.20.0.20 ansible_user=platform
k3s-worker-node ansible_host=10.20.0.21 ansible_user=worker


#------Configs-----#
[lxcs:vars]
# SSH Keys for All LXC Nodes
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/ansible

[vms:vars]
# Shared key across all VMs -- ansible_user now set per-host above instead
ansible_ssh_private_key_file=~/.ssh/ansible