#------Nodes------#
[lxcs]
# Technitium Internal DNS server
10.10.0.20
# Hashicorp Vault
10.10.0.30
# Github CI/CD Runner
10.10.0.40

#------Configs-----#
[lxcs:vars]
# SSH Keys for All Nodes 
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/ansible
